//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EZPCEntidades : DbContext
    {
        public EZPCEntidades()
            : base("name=EZPCEntidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarritoItem> CarritoItems { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Ciudad> Ciudades { get; set; }
        public virtual DbSet<Contacto> Contactos { get; set; }
        public virtual DbSet<Cupon> Cupones { get; set; }
        public virtual DbSet<Direccion> Direcciones { get; set; }
        public virtual DbSet<Estado> Estados { get; set; }
        public virtual DbSet<MetodoPago> MetodosPago { get; set; }
        public virtual DbSet<Orden> Ordenes { get; set; }
        public virtual DbSet<OrdenItem> OrdenItems { get; set; }
        public virtual DbSet<Pais> Paises { get; set; }
        public virtual DbSet<Producto> Productos { get; set; }
        public virtual DbSet<TipoUsuario> TiposUsuario { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Oferta> Ofertas { get; set; }
    }
}
