//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orden()
        {
            this.OrdenItem = new HashSet<OrdenItem>();
        }
    
        public int id { get; set; }
        public Nullable<decimal> costo_total { get; set; }
        public System.DateTime fecha_compra { get; set; }
        public int id_pago { get; set; }
        public int id_direccion { get; set; }
        public int id_usuario { get; set; }
        public Nullable<int> id_cupon { get; set; }
    
        public virtual Cupon Cupon { get; set; }
        public virtual Direccion Direccion { get; set; }
        public virtual MetodoPago MetodoPago { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenItem> OrdenItem { get; set; }
    }
}
